# Generated by Django 3.2 on 2021-04-18 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_artista_teste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artista',
            name='teste',
            field=models.ImageField(upload_to='Artistas'),
        ),
    ]
