# Generated by Django 3.2 on 2021-04-20 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_artista_teste'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='teste',
        ),
        migrations.AlterField(
            model_name='artista',
            name='art_imagem',
            field=models.ImageField(upload_to='Artistas'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='not_imagem',
            field=models.ImageField(upload_to='Artigos'),
        ),
        migrations.AlterField(
            model_name='obras',
            name='obr_img',
            field=models.ImageField(upload_to='Obras'),
        ),
    ]
