# Generated by Django 3.2 on 2021-05-01 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210430_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='not_publi',
            field=models.DateField(verbose_name='Data de publicação'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='not_tipo',
            field=models.CharField(choices=[('N', 'Notícia'), ('A', 'Artigo'), ('E', 'Entrevista')], max_length=1, verbose_name='Tipo da publicação:'),
        ),
        migrations.AlterModelTable(
            name='obras',
            table='obra',
        ),
    ]
