# Generated by Django 3.2 on 2021-05-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210501_1422'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Obras',
            new_name='Obra',
        ),
        migrations.AddField(
            model_name='artista',
            name='art_legenda',
            field=models.CharField(max_length=200, null=True, verbose_name='Legenda do Artista'),
        ),
        migrations.AddField(
            model_name='noticia',
            name='not_legenda',
            field=models.CharField(max_length=200, null=True, verbose_name='Legenda da noticia'),
        ),
    ]
