# Generated by Django 3.2 on 2021-05-10 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210508_1529'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artista',
            name='art_sobrenome',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='not_nome',
            field=models.CharField(max_length=100, verbose_name='Titulo da publicação:'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='not_tipo',
            field=models.CharField(choices=[('A', 'Artigo'), ('E', 'Entrevista')], max_length=1, verbose_name='Tipo da publicação:'),
        ),
        migrations.AlterField(
            model_name='obra',
            name='obr_nome',
            field=models.CharField(max_length=200, verbose_name='Título da obra:'),
        ),
    ]
